version: '3'
services:
  consumer:
    container_name: consumer
    build:
      context: ./consumer
      dockerfile: Dockerfile
    depends_on:
      - kafka
    restart: always

  producer:
    container_name: producer
    build:
      context: ./producer
      dockerfile: Dockerfile
    depends_on:
      - kafka
    restart: always

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - '9092:9092'
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
    restart: always

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - '2181:2181'